[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]  
repo = 'airblade/vim-gitgutter'

[[plugins]]  
repo = 'neoclide/coc.nvim'
merged = 0
rev = "release"
