[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeToggle']

[[plugins]]
repo = 'dense-analysis/ale'

[[plugins]]
repo = 'ervandew/supertab'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'maximbaz/lightline-ale'

[[plugins]]  
repo = 'airblade/vim-gitgutter'

[[plugins]]  
repo = 'neoclide/coc.nvim'
merged = 0
rev = "release"

[[plugins]]
repo = 'SirVer/ultisnips'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]  
repo = 'junegunn/fzf'  
build = './install --bin'  
merged = '0'

[[plugins]]  
repo = 'junegunn/fzf.vim'  
depends = 'fzf'

[[plugins]]  
repo = 'tpope/vim-fugitive'
