version: "3"

services:
    app:
        container_name: my_env
        image: my_env
        working_dir: /usr/src/app
        volumes:
            - ./:/usr/src/app
        cap_add:
            - SYS_ADMIN
        devices:
            - /dev/fuse
        networks:
            - app_net

networks:
    app_net:
        driver: bridge
