local plugins = {
    'ale',
    'nerdtree',
    'molokai',
    'lightline',
    'lightline-ale',
    'vim-gitgutter',
    'coc',
    'ultisnips',
    'vim-snippets',
    'neoterm',
    'fzf',
    'fzf_vim',
    'vim-fugitive',
    'winresizer',
    'vim-quickrun',
    'copilot',
    'remote-nvim',
    'noice',
    'vim-toml',
    'python-syntax',
    'previm',
}

return plugins
