local plugins = {
    --'ale',
    'molokai',
    'nvimtree',
    'lightline',
    'lightline-ale',
    'vim-gitgutter',
    'ultisnips',
    'vim-snippets',
    'neoterm',
    'fzf',
    'fzf_vim',
    'vim-fugitive',
    'winresizer',
    'vim-quickrun',
    'copilot',
    'copilotchat',
    'remote-nvim',
    --'noice',
    'vim-toml',
    'python-syntax',
    'previm',
    'mason-lspconfig',
    'lspsaga',
    'nvim-cmp',
}

return plugins
